version: '3'

services:
  front:
    build: ./docker/front
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=local
    volumes:
      - ./front:/usr/src/app
    command: npm start
    ports:
      - '3000:3000'
    tty: true
  
  back:
    build: ./docker/json-server
    volumes: 
      - ./docker/json-server/db.json:/data/db.json
    command: json-server --watch db.json --port 3001 --host 0.0.0.0
    ports:
      - '3001:3001'
    tty: true