version: '3'

services:
  front:
    build: ./docker/front
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./front:/usr/src/app
    command: sh -c 'yarn start'
    ports:
      - '3000:3000'
    tty: true